AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Dynamo Stream Orchestrator Lambda Function

Resources:
  DynamoStreamOrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dynamo_stream_orchestrator/
      Handler: function.lambda_handler
      Runtime: python3.13
      PackageType: Zip
      Architectures:
        - arm64
      Environment:
        Variables:
          # Dev hem-model-runs-step-function
          STATE_MACHINE_ARN: "arn:aws:states:eu-west-2:864981718509:stateMachine:hem-model-runs-step-function"
