AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  HEM Lambda Function

Resources:
  HEMLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - arm64
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hem_eval_function
      DockerTag: python3.9-hem

  DynamoStreamOrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dynamo_stream_orchestrator/
      Handler: function.lambda_handler
      Runtime: python3.13
      PackageType: Zip
      Architectures:
        - arm64
